version: "3.8"
services:
    mytruyen-db:
        container_name: mytruyen-db
        image: postgres:15
        env_file:
            - .env
        ports:
            - ${POSTGRES_EXTERNAL_PORT}:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - mytruyen-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
                ]
            interval: 10s
            timeout: 10s
            retries: 5

    mytruyen-be:
        container_name: mytruyen-be
        image: hoangphat120805/mytruyen-be:latest
        env_file:
            - .env
        depends_on:
            mytruyen-db:
                condition: service_healthy
        ports:
            - "8000:8000"
        networks:
            - mytruyen-net
        command: >
            bash -c "
            alembic upgrade head &&
            fastapi run app/main.py --workers 4
            "
    
    mytruyen-redis:
        container_name: mytruyen-redis
        image: redis:7
        env_file:
            - .env
        ports:
        - "6379:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
        - mytruyen-net
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    meilisearch:
        container_name: meilisearch
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        restart: always
        environment:
        - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
        - MEILI_ENV=production
        - MEILI_NO_ANALYTICS=true
        ports:
        - "7700:7700"
        volumes:
        - meili_data:/meili_data
    
    services:
        rabbitmq:
            container_name: rabbitmq
            image: rabbitmq:3-management-alpine
            container_name: rabbitmq_server
            ports:
            - "5672:5672"
            - "15672:15672"
            environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

volumes:
    db-data:
    meili_data:

networks:
    mytruyen-net:
        driver: bridge
