"""add cascade delete for genre and tag

Revision ID: 0c4042c59c3f
Revises: db79482237c2
Create Date: 2025-10-29 19:08:17.605029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0c4042c59c3f'
down_revision: Union[str, Sequence[str], None] = 'db79482237c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_genre_link_genre_id_genre'), 'book_genre_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_link_book_id_book'), 'book_genre_link', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_genre_link_book_id_book'), 'book_genre_link', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_book_genre_link_genre_id_genre'), 'book_genre_link', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_book_tag_link_book_id_book'), 'book_tag_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_tag_link_tag_id_tag'), 'book_tag_link', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_tag_link_book_id_book'), 'book_tag_link', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_book_tag_link_tag_id_tag'), 'book_tag_link', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_tag_link_tag_id_tag'), 'book_tag_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_tag_link_book_id_book'), 'book_tag_link', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_tag_link_tag_id_tag'), 'book_tag_link', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('fk_book_tag_link_book_id_book'), 'book_tag_link', 'book', ['book_id'], ['id'])
    op.drop_constraint(op.f('fk_book_genre_link_genre_id_genre'), 'book_genre_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_genre_link_book_id_book'), 'book_genre_link', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_genre_link_book_id_book'), 'book_genre_link', 'book', ['book_id'], ['id'])
    op.create_foreign_key(op.f('fk_book_genre_link_genre_id_genre'), 'book_genre_link', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
