"""add genre table

Revision ID: 1429fa71e2d5
Revises: c31e7058d0fc
Create Date: 2025-09-28 14:24:54.845575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1429fa71e2d5'
down_revision: Union[str, Sequence[str], None] = 'c31e7058d0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre'))
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_index(op.f('ix_genre_slug'), 'genre', ['slug'], unique=True)
    op.add_column('book', sa.Column('genre_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_book_genre_id_genre'), 'book', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_genre_id_genre'), 'book', type_='foreignkey')
    op.drop_column('book', 'genre_id')
    op.drop_index(op.f('ix_genre_slug'), table_name='genre')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
