"""update book, genre and comment

Revision ID: 1871ec41ed8e
Revises: e12f17175524
Create Date: 2025-10-11 08:21:38.752782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1871ec41ed8e'
down_revision: Union[str, Sequence[str], None] = 'e12f17175524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('bookmark_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('poster', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('book', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comment', sa.Column('chapter_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('fk_comment_book_id_book'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_chapter_id_chapter'), 'comment', 'chapter', ['chapter_id'], ['id'])
    op.drop_column('comment', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_comment_chapter_id_chapter'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_book_id_book'), 'comment', 'book', ['book_id'], ['id'])
    op.drop_column('comment', 'chapter_id')
    op.drop_column('book', 'note')
    op.drop_column('book', 'poster')
    op.drop_column('book', 'bookmark_count')
    # ### end Alembic commands ###
