"""add new_chapter_at

Revision ID: 37edd76b4010
Revises: adb8ed83c5ad
Create Date: 2025-12-20 14:43:51.176128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '37edd76b4010'
down_revision: Union[str, Sequence[str], None] = 'adb8ed83c5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('new_chapter_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'new_chapter_at')
    # ### end Alembic commands ###
