"""add type for tag

Revision ID: 53a47be9153d
Revises: fd4d73290010
Create Date: 2025-10-23 23:47:41.759692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '53a47be9153d'
down_revision: Union[str, Sequence[str], None] = 'fd4d73290010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_tag_type'), 'tag', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_type'), table_name='tag')
    op.drop_column('tag', 'type')
    # ### end Alembic commands ###
