"""update field name new chap at

Revision ID: 57f1f16d6951
Revises: 37edd76b4010
Create Date: 2025-12-20 14:49:12.335846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f1f16d6951'
down_revision: Union[str, Sequence[str], None] = '37edd76b4010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('new_chap_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('book', 'new_chapter_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('new_chapter_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('book', 'new_chap_at')
    # ### end Alembic commands ###
