"""add creator into chapter

Revision ID: c305d8b7bafc
Revises: feaf5a6953b5
Create Date: 2025-10-26 20:02:06.810132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c305d8b7bafc'
down_revision: Union[str, Sequence[str], None] = 'feaf5a6953b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('fk_chapter_author_id_user'), 'chapter', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_creator_id_user'), 'chapter', 'user', ['creator_id'], ['id'])
    op.drop_column('chapter', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_chapter_creator_id_user'), 'chapter', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_author_id_user'), 'chapter', 'user', ['author_id'], ['id'])
    op.drop_column('chapter', 'creator_id')
    # ### end Alembic commands ###
