"""update add enum and alotof att

Revision ID: c31e7058d0fc
Revises: 897809416033
Create Date: 2025-09-25 12:11:58.305357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c31e7058d0fc'
down_revision: Union[str, Sequence[str], None] = '897809416033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_comment_book_id_book')),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_review_book_id_book')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_table('chapter_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_chapter_content_chapter_id_chapter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter_content')),
    sa.UniqueConstraint('chapter_id', name=op.f('uq_chapter_content_chapter_id'))
    )
    op.drop_table('chaptercontent')
    op.add_column('book', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.add_column('book', sa.Column('chapter_per_week', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('book', sa.Column('latest_chapter', sa.Uuid(), nullable=True))
    op.add_column('book', sa.Column('synopsis', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('book', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('chapter_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('comment_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('review_count', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('average_rating', sa.Float(), nullable=False))
    op.add_column('book', sa.Column('published_at', sa.DateTime(), nullable=True))
    book_status = sa.Enum('ONGOING', 'COMPLETED', 'PAUSED', name='book_status')
    book_status.create(op.get_bind(), checkfirst=True)
    op.alter_column('book', 'status',
               existing_type=sa.INTEGER(),
               type_=book_status,
               postgresql_using="status::text::book_status",
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_book_author_id_user'), 'book', 'user', ['author_id'], ['id'])
    op.add_column('chapter', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.add_column('chapter', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('chapter', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('chapter', sa.Column('comment_count', sa.Integer(), nullable=False))
    op.add_column('chapter', sa.Column('published', sa.Boolean(), nullable=False))
    op.add_column('chapter', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(op.f('uq_chapter_index'), 'chapter', ['index'])
    op.create_foreign_key(op.f('fk_chapter_author_id_user'), 'chapter', 'user', ['author_id'], ['id'])
    user_role = sa.Enum('USER', 'ADMIN', name='user_role')
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', user_role, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    user_role = sa.Enum('USER', 'ADMIN', name='user_role')
    user_role.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(op.f('fk_chapter_author_id_user'), 'chapter', type_='foreignkey')
    op.drop_constraint(op.f('uq_chapter_index'), 'chapter', type_='unique')
    op.drop_column('chapter', 'published_at')
    op.drop_column('chapter', 'published')
    op.drop_column('chapter', 'comment_count')
    op.drop_column('chapter', 'view_count')
    op.drop_column('chapter', 'word_count')
    op.drop_column('chapter', 'author_id')
    op.drop_constraint(op.f('fk_book_author_id_user'), 'book', type_='foreignkey')
    book_status = sa.Enum('ONGOING', 'COMPLETED', 'PAUSED', name='book_status')
    op.alter_column('book', 'status',
               existing_type=book_status,
               type_=sa.INTEGER(),
                postgresql_using="status::text::integer",
               existing_nullable=False)
    book_status.drop(op.get_bind(), checkfirst=True)
    op.drop_column('book', 'published_at')
    op.drop_column('book', 'average_rating')
    op.drop_column('book', 'review_count')
    op.drop_column('book', 'comment_count')
    op.drop_column('book', 'word_count')
    op.drop_column('book', 'chapter_count')
    op.drop_column('book', 'view_count')
    op.drop_column('book', 'synopsis')
    op.drop_column('book', 'latest_chapter')
    op.drop_column('book', 'published')
    op.drop_column('book', 'chapter_per_week')
    op.drop_column('book', 'author_id')
    op.create_table('chaptercontent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_chaptercontent_chapter_id_chapter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chaptercontent'))
    )
    op.drop_table('chapter_content')
    op.drop_table('review')
    op.drop_table('comment')
    # ### end Alembic commands ###
