"""add casecading delete to schema

Revision ID: db79482237c2
Revises: c305d8b7bafc
Create Date: 2025-10-28 14:59:20.393339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'db79482237c2'
down_revision: Union[str, Sequence[str], None] = 'c305d8b7bafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_creator_id'), 'book', ['creator_id'], unique=False)
    op.create_index(op.f('ix_chapter_book_id'), 'chapter', ['book_id'], unique=False)
    op.create_index(op.f('ix_chapter_creator_id'), 'chapter', ['creator_id'], unique=False)
    op.drop_constraint(op.f('fk_chapter_creator_id_user'), 'chapter', type_='foreignkey')
    op.drop_constraint(op.f('fk_chapter_book_id_book'), 'chapter', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_creator_id_user'), 'chapter', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_chapter_book_id_book'), 'chapter', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_chapter_content_chapter_id_chapter'), 'chapter_content', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_content_chapter_id_chapter'), 'chapter_content', 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_comment_chapter_id'), 'comment', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_comment_user_id_user'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('fk_comment_chapter_id_chapter'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_user_id_user'), 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comment_chapter_id_chapter'), 'comment', 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_review_book_id'), 'review', ['book_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_review_user_id_user'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_book_id_book'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_book_id_book'), 'review', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_review_user_id_user'), 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_review_user_id_user'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_book_id_book'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_book_id_book'), 'review', 'book', ['book_id'], ['id'])
    op.create_foreign_key(op.f('fk_review_user_id_user'), 'review', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_book_id'), table_name='review')
    op.drop_constraint(op.f('fk_comment_chapter_id_chapter'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('fk_comment_user_id_user'), 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_chapter_id_chapter'), 'comment', 'chapter', ['chapter_id'], ['id'])
    op.create_foreign_key(op.f('fk_comment_user_id_user'), 'comment', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_chapter_id'), table_name='comment')
    op.drop_constraint(op.f('fk_chapter_content_chapter_id_chapter'), 'chapter_content', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_content_chapter_id_chapter'), 'chapter_content', 'chapter', ['chapter_id'], ['id'])
    op.drop_constraint(op.f('fk_chapter_book_id_book'), 'chapter', type_='foreignkey')
    op.drop_constraint(op.f('fk_chapter_creator_id_user'), 'chapter', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_book_id_book'), 'chapter', 'book', ['book_id'], ['id'])
    op.create_foreign_key(op.f('fk_chapter_creator_id_user'), 'chapter', 'user', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_chapter_creator_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_book_id'), table_name='chapter')
    op.drop_index(op.f('ix_book_creator_id'), table_name='book')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    # ### end Alembic commands ###
