"""remove genre_id from book

Revision ID: e12f17175524
Revises: e4f5c0516b97
Create Date: 2025-10-09 16:17:46.623819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e12f17175524'
down_revision: Union[str, Sequence[str], None] = 'e4f5c0516b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_genre_id_genre'), 'book', type_='foreignkey')
    op.drop_column('book', 'genre_id')
    op.drop_column('genre_book', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre_book', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('book', sa.Column('genre_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_book_genre_id_genre'), 'book', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
