"""add table book_genre

Revision ID: e4f5c0516b97
Revises: 1429fa71e2d5
Create Date: 2025-10-09 10:07:29.824491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e4f5c0516b97'
down_revision: Union[str, Sequence[str], None] = '1429fa71e2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_book',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_genre_book_book_id_book')),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_genre_book_genre_id_genre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre_book'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_book')
    # ### end Alembic commands ###
