"""update jsomb for book's poster

Revision ID: e5e1aa9e5f4d
Revises: 1871ec41ed8e
Create Date: 2025-10-13 08:52:17.617206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5e1aa9e5f4d'
down_revision: Union[str, Sequence[str], None] = '1871ec41ed8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'book',
        'poster',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        postgresql_using="poster::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'poster',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
