"""add table author

Revision ID: feaf5a6953b5
Revises: 53a47be9153d
Create Date: 2025-10-25 11:01:36.663304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'feaf5a6953b5'
down_revision: Union[str, Sequence[str], None] = '53a47be9153d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author'))
    )
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=True)
    op.add_column('book', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.alter_column('book', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('fk_book_author_id_user'), 'book', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_author_id_author'), 'book', 'author', ['author_id'], ['id'])
    op.create_foreign_key(op.f('fk_book_creator_id_user'), 'book', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_creator_id_user'), 'book', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_author_id_author'), 'book', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_author_id_user'), 'book', 'user', ['author_id'], ['id'])
    op.alter_column('book', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('book', 'creator_id')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
